// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "cuenta_nueva.h"
/**
   mueve esto a un enum class de la clase cuenta
*/
static const int idx_cuenta[] = {0,1,2,3,4,5};

/**
   callback de seleccion de tipo de cuenta
*/
static void tipo_cb(Fl_Button *b, void* p) {
  using namespace std;
  int i = *(int*)p;
  cout << i << endl;
}

int ventana_cuenta_nueva() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(276, 316, "Crear cuenta");
    w = o;
    { new Fl_Button(185, 270, 80, 30, "cancelar");
    } // Fl_Button* o
    { new Fl_Return_Button(90, 270, 85, 30, "Crear");
    } // Fl_Return_Button* o
    { Fl_Group* o = new Fl_Group(10, 25, 75, 110, "Tipo");
      o->box(FL_GTK_UP_FRAME);
      o->labelfont(8);
      { Fl_Round_Button* o = new Fl_Round_Button(10, 35, 64, 15, "Activo");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*) tipo_cb, (void*)(idx_cuenta));
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 50, 64, 15, "Pasivo");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->user_data((void*)(1));
        o->callback((Fl_Callback*) tipo_cb, (void*)(idx_cuenta+1));
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 66, 64, 15, "Capital");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*) tipo_cb, (void*)(idx_cuenta+2));
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 100, 64, 15, "Gastos");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*) tipo_cb, (void*)(idx_cuenta+3));
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(10, 115, 64, 15, "Ingresos");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*) tipo_cb, (void*)(idx_cuenta+4));
      } // Fl_Round_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(130, 25, 70, 55, "Subtipo");
      o->box(FL_GTK_UP_FRAME);
      o->labelfont(8);
      { Fl_Round_Button* o = new Fl_Round_Button(135, 35, 64, 15);
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(135, 50, 64, 15);
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
      } // Fl_Round_Button* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  using namespace std;
  /* codigo pendiente */
  w->show();
  w->end();
  return 0;
}
