// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef cuenta_nueva_h
#define cuenta_nueva_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <iostream>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
int ventana_cuenta_nueva();
#endif
